const Accounting=(()=>{
 const money=v=>new Intl.NumberFormat('tr-TR',{style:'currency',currency:'TRY'}).format(Number(v)||0);
 const val=id=>document.querySelector(id)?.value?.trim?.()||'';
 const num=id=>Number(String(val(id)).replace(',','.'))||0;
 const trType={income:'Gelir',expense:'Gider',collection:'Tahsilat',payment:'Ödeme',purchase:'Alış',sale:'Satış'};
 async function openView(view){
  if(view==='stock')await renderStock();
  if(view==='customers')await renderParties();
  if(view==='invoices')await renderInvoices();
  if(view==='finance')await renderFinance();
  if(view==='accountingReports')await renderReports();
 }
 async function renderStock(){
  let products=await KDB.all('products'),q=(val('#stockSearch')||'').toLocaleLowerCase('tr-TR');if(q)products=products.filter(p=>`${p.productName} ${p.barcode} ${p.productCode||''}`.toLocaleLowerCase('tr-TR').includes(q));
  document.querySelector('#stockTable').innerHTML=products.length?`<table class="data-table"><thead><tr><th>Ürün</th><th>Barkod</th><th>Stok</th><th class="admin-only">Alış</th><th class="admin-only">Satış</th></tr></thead><tbody>${products.slice(0,800).map(p=>`<tr><td><b>${esc(p.productName)}</b></td><td>${esc(p.barcode)}</td><td><b>${Number(p.currentStock)||0}</b> ${esc(p.unit||'ADET')}</td><td class="admin-only">${money(p.purchasePrice)}</td><td class="admin-only">${money(p.salePrice)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Ürün bulunamadı.</div>';
  document.querySelectorAll('#view-stock .admin-only').forEach(x=>x.classList.toggle('hidden',session?.role!=='ADMIN'));
  const counts=(await KDB.all('stockCounts')).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));
  document.querySelector('#countTable').innerHTML=counts.length?`<table class="data-table"><thead><tr><th>Tarih</th><th>Personel</th><th>Not</th><th>Durum</th><th></th></tr></thead><tbody>${counts.map(c=>`<tr><td>${fmtDate(c.countDate)}</td><td>${esc(c.createdByName||'—')}</td><td>${esc(c.notes||'—')}</td><td><span class="pill ${c.status==='approved'?'green':'orange'}">${c.status==='approved'?'Onaylandı':c.status==='rejected'?'Reddedildi':'Onay Bekliyor'}</span></td><td>${session?.role==='ADMIN'&&c.status==='pending'?`<button class="mini-btn" data-approve-count="${c.id}">Onayla ve Stoka İşle</button>`:''}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Henüz sayım girilmedi.</div>';
 }
 async function saveCount(){
  const barcode=val('#countBarcode'),counted=num('#countQuantity');if(!barcode)return toast('Barkod girin.');if(counted<0)return toast('Sayılan adet negatif olamaz.');const product=await KDB.findProduct(barcode);if(!product)return toast('Bu barkod ürün listesinde bulunamadı.');
  const id=crypto.randomUUID(),date=new Date().toISOString();await KDB.put('stockCounts',{id,countDate:date.slice(0,10),status:'pending',notes:val('#countNote'),createdBy:session.id,createdByName:session.name,createdAt:date,updatedAt:date});await KDB.put('stockCountLines',{id:crypto.randomUUID(),countId:id,barcode:product.barcode,productName:product.productName,systemQuantity:Number(product.currentStock)||0,countedQuantity:counted,differenceQuantity:counted-(Number(product.currentStock)||0),createdAt:date,updatedAt:date});await KDB.log(session,'STOCK_COUNT','stock_count',id,`${product.productName}: ${counted} adet sayıldı.`);document.querySelector('#countBarcode').value='';document.querySelector('#countQuantity').value='';toast('Sayım yönetici onayına gönderildi.');await renderStock();
 }
 async function approveCount(id){if(!confirm('Sayım farkı merkezi stoka işlensin mi?'))return;const {data,error}=await KStaff.connect().rpc('approve_stock_count',{p_local_id:id});if(error)return toast(error.message);await KDB.sync();toast('Sayım onaylandı ve stok güncellendi.');await renderStock();}
 async function saveParty(){
  const type=val('#partyType'),name=val('#partyName');if(!name)return toast('Cari unvanını girin.');const base={id:crypto.randomUUID(),name,phone:val('#partyPhone'),taxNumber:val('#partyTax'),openingBalance:num('#partyBalance'),notes:'',createdAt:now(),updatedAt:now()};await KDB.put(type==='supplier'?'suppliers':'customers',base);toast('Cari kart kaydedildi.');['#partyName','#partyPhone','#partyTax'].forEach(x=>document.querySelector(x).value='');await renderParties();
 }
 async function renderParties(){const [customers,suppliers]=await Promise.all([KDB.all('customers'),KDB.all('suppliers')]);const rows=[...customers.map(x=>({...x,kind:'Müşteri'})),...suppliers.map(x=>({...x,kind:'Tedarikçi'}))].sort((a,b)=>a.name.localeCompare(b.name,'tr'));document.querySelector('#partyTable').innerHTML=rows.length?`<table class="data-table"><thead><tr><th>Tür</th><th>Unvan</th><th>Telefon</th><th>Vergi No</th><th>Açılış</th></tr></thead><tbody>${rows.map(x=>`<tr><td><span class="pill blue">${x.kind}</span></td><td><b>${esc(x.name)}</b></td><td>${esc(x.phone||'—')}</td><td>${esc(x.taxNumber||'—')}</td><td>${money(x.openingBalance)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Cari kart bulunmuyor.</div>'}
 async function invoiceOptions(){const type=val('#invoiceType')||'purchase',[products,parties]=await Promise.all([KDB.all('products'),KDB.all(type==='purchase'?'suppliers':'customers')]);document.querySelector('#invoiceParty').innerHTML='<option value="">Cari seçin</option>'+parties.sort((a,b)=>a.name.localeCompare(b.name,'tr')).map(x=>`<option value="${x.id}">${esc(x.name)}</option>`).join('');document.querySelector('#invoiceProduct').innerHTML='<option value="">Ürün seçin</option>'+products.sort((a,b)=>a.productName.localeCompare(b.productName,'tr')).map(x=>`<option value="${x.barcode}">${esc(x.productName)} • ${esc(x.barcode)}</option>`).join('')}
 async function saveInvoice(){
  if(!navigator.onLine)return toast('Finansal bütünlük için fatura kaydı çevrimiçi yapılır.');const type=val('#invoiceType'),partyId=val('#invoiceParty'),barcode=val('#invoiceProduct'),quantity=num('#invoiceQuantity'),unitPrice=num('#invoiceUnitPrice'),vatRate=num('#invoiceVat');if(!partyId||!barcode||quantity<=0)return toast('Cari, ürün ve miktarı kontrol edin.');const payload={invoice_type:type,document_number:val('#accountingInvoiceNo'),invoice_date:val('#accountingInvoiceDate')||today(),party_local_id:partyId,barcode,quantity,unit_price:unitPrice,vat_rate:vatRate,notes:val('#invoiceNote'),local_id:crypto.randomUUID()};const {error}=await KStaff.connect().rpc('post_simple_invoice',{p_data:payload});if(error)return toast(error.message);await KDB.sync();toast('Fatura ve stok hareketi kaydedildi.');await renderInvoices();
 }
 async function renderInvoices(){await invoiceOptions();const list=(await KDB.all('invoices')).sort((a,b)=>b.invoiceDate.localeCompare(a.invoiceDate));document.querySelector('#invoiceTable').innerHTML=list.length?`<table class="data-table"><thead><tr><th>Tarih</th><th>Tür</th><th>Belge</th><th>Cari</th><th>Tutar</th><th>Durum</th></tr></thead><tbody>${list.map(x=>`<tr><td>${fmtDate(x.invoiceDate)}</td><td><span class="pill ${x.invoiceType==='purchase'?'orange':'green'}">${trType[x.invoiceType]}</span></td><td>${esc(x.documentNumber||'—')}</td><td><b>${esc(x.supplierName||x.customerName||'—')}</b></td><td>${money(x.grandTotal)}</td><td>${esc(x.paymentStatus||'unpaid')}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Fatura bulunmuyor.</div>'}
 async function saveAccount(){const name=val('#accountName');if(!name)return toast('Hesap adını girin.');await KDB.put('accounts',{id:crypto.randomUUID(),name,accountType:val('#accountType'),currency:'TRY',openingBalance:num('#accountOpening'),active:true,createdAt:now(),updatedAt:now()});toast('Hesap kaydedildi.');document.querySelector('#accountName').value='';await renderFinance()}
 async function saveTransaction(){const accountId=val('#transactionAccount'),amount=num('#transactionAmount');if(!accountId||amount<=0)return toast('Hesap ve tutarı kontrol edin.');await KDB.put('financialTransactions',{id:crypto.randomUUID(),accountId,transactionType:val('#transactionType'),amount,transactionDate:today(),description:val('#transactionDescription'),documentNumber:'',createdBy:session.id,createdByName:session.name,createdAt:now(),updatedAt:now()});toast('Para hareketi kaydedildi.');await renderFinance()}
 async function renderFinance(){const [accounts,txs]=await Promise.all([KDB.all('accounts'),KDB.all('financialTransactions')]);const sums=new Map(accounts.map(a=>[a.id,Number(a.openingBalance)||0]));for(const t of txs)sums.set(t.accountId,(sums.get(t.accountId)||0)+(['income','collection','transfer_in'].includes(t.transactionType)?Number(t.amount):-Number(t.amount)));document.querySelector('#transactionAccount').innerHTML='<option value="">Hesap seçin</option>'+accounts.map(a=>`<option value="${a.id}">${esc(a.name)}</option>`).join('');document.querySelector('#accountCards').innerHTML=accounts.map(a=>`<div class="metric"><span>${esc(a.name)} • ${a.accountType==='cash'?'Kasa':'Banka'}</span><strong>${money(sums.get(a.id))}</strong></div>`).join('')||'<div class="empty-state">Hesap yok.</div>';const sorted=txs.sort((a,b)=>b.createdAt.localeCompare(a.createdAt));document.querySelector('#transactionTable').innerHTML=sorted.length?`<table class="data-table"><thead><tr><th>Tarih</th><th>Hesap</th><th>İşlem</th><th>Açıklama</th><th>Tutar</th></tr></thead><tbody>${sorted.map(t=>`<tr><td>${fmtDate(t.transactionDate)}</td><td>${esc(accounts.find(a=>a.id===t.accountId)?.name||'—')}</td><td>${trType[t.transactionType]||t.transactionType}</td><td>${esc(t.description||'—')}</td><td class="${['income','collection'].includes(t.transactionType)?'money-in':'money-out'}">${money(t.amount)}</td></tr>`).join('')}</tbody></table>`:'<div class="empty-state">Hareket yok.</div>'}
 async function renderReports(){const [invoices,products,customers,suppliers,accounts,txs]=await Promise.all(['invoices','products','customers','suppliers','accounts','financialTransactions'].map(x=>KDB.all(x)));const sales=invoices.filter(x=>x.invoiceType==='sale').reduce((s,x)=>s+Number(x.grandTotal),0),purchases=invoices.filter(x=>x.invoiceType==='purchase').reduce((s,x)=>s+Number(x.grandTotal),0),stockValue=products.reduce((s,x)=>s+(Number(x.currentStock)||0)*(Number(x.purchasePrice)||0),0),cash=accounts.reduce((s,a)=>s+Number(a.openingBalance||0),0)+txs.reduce((s,t)=>s+(['income','collection','transfer_in'].includes(t.transactionType)?Number(t.amount):-Number(t.amount)),0);document.querySelector('#accountingMetrics').innerHTML=[['Toplam Satış',sales],['Toplam Alış',purchases],['Kasa + Banka',cash],['Stok Maliyeti',stockValue]].map(([k,v])=>`<div class="metric"><span>${k}</span><strong>${money(v)}</strong></div>`).join('');document.querySelector('#accountingPartyReport').innerHTML=`<table class="data-table"><thead><tr><th>Tür</th><th>Adet</th></tr></thead><tbody><tr><td>Müşteri</td><td>${customers.length}</td></tr><tr><td>Tedarikçi</td><td>${suppliers.length}</td></tr></tbody></table>`;document.querySelector('#stockValueReport').innerHTML=`<table class="data-table"><thead><tr><th>Ürün</th><th>Stok</th><th>Maliyet Değeri</th></tr></thead><tbody>${products.sort((a,b)=>(b.currentStock*b.purchasePrice)-(a.currentStock*a.purchasePrice)).slice(0,100).map(p=>`<tr><td>${esc(p.productName)}</td><td>${Number(p.currentStock)||0}</td><td>${money((Number(p.currentStock)||0)*(Number(p.purchasePrice)||0))}</td></tr>`).join('')}</tbody></table>`}
 const pick=(row,names)=>{const keys=Object.keys(row),key=keys.find(k=>names.includes(k.toLocaleLowerCase('tr-TR').trim()));return key?row[key]:''};
 async function importAkinsoft(){const file=document.querySelector('#akinsoftFile').files[0],type=val('#akinsoftImportType');if(!file)return toast('Excel veya CSV dosyası seçin.');const wb=XLSX.read(await file.arrayBuffer(),{type:'array'}),rows=XLSX.utils.sheet_to_json(wb.Sheets[wb.SheetNames[0]],{defval:''});let ok=0,skip=0;for(const row of rows){const name=String(pick(row,['adı','adi','ünvan','unvan','cari adı','cari adi','ürün adı','urun adi','stok adı','stok adi'])).trim(),barcode=String(pick(row,['barkod','barcode','barkodu'])).trim();try{if(type==='customers'&&name)await KDB.put('customers',{id:crypto.randomUUID(),name,phone:String(pick(row,['telefon','tel'])),taxNumber:String(pick(row,['vergi no','vkn'])),openingBalance:Number(pick(row,['bakiye','açılış bakiyesi','acilis bakiyesi']))||0,createdAt:now(),updatedAt:now()});else if(type==='suppliers'&&name)await KDB.put('suppliers',{id:crypto.randomUUID(),name,phone:String(pick(row,['telefon','tel'])),taxNumber:String(pick(row,['vergi no','vkn'])),createdAt:now(),updatedAt:now()});else if(type==='products'&&barcode){const old=await KDB.get('products',barcode);await KDB.put('products',{...(old||{}),barcode,productCode:String(pick(row,['ürün kodu','urun kodu','stok kodu'])),productName:name||barcode,unit:String(pick(row,['birim'])).toUpperCase()||'ADET',purchasePrice:Number(pick(row,['alış fiyatı','alis fiyati','alış','alis']))||old?.purchasePrice||0,salePrice:Number(pick(row,['satış fiyatı','satis fiyati','satış','satis']))||old?.salePrice||0,vatRate:Number(pick(row,['kdv','kdv oranı','kdv orani']))||1,manuallyAdded:false,createdAt:old?.createdAt||now(),updatedAt:now()})}else if(type==='opening_stock'&&barcode){const p=await KDB.findProduct(barcode),qty=Number(pick(row,['stok','miktar','mevcut stok']))||0;if(!p)throw new Error('Ürün yok');await KDB.put('stockMovements',{id:crypto.randomUUID(),barcode,productName:p.productName,movementType:'opening',quantity:qty,unitCost:p.purchasePrice||0,movementDate:today(),referenceType:'akinsoft',referenceId:file.name,description:'AKINSOFT açılış stoğu',createdBy:session.id,createdByName:session.name,createdAt:now(),updatedAt:now()})}else{skip++;continue}ok++}catch{skip++}}document.querySelector('#akinsoftImportResult').innerHTML=`<div class="info-strip"><b>${ok}</b> kayıt aktarıldı, <b>${skip}</b> satır atlandı.</div>`;toast('AKINSOFT aktarımı tamamlandı.')}
 function bind(){document.querySelector('#stockSearch')?.addEventListener('input',renderStock);document.querySelector('#saveCountBtn')?.addEventListener('click',saveCount);document.querySelector('#savePartyBtn')?.addEventListener('click',saveParty);document.querySelector('#invoiceType')?.addEventListener('change',invoiceOptions);document.querySelector('#saveInvoiceBtn')?.addEventListener('click',saveInvoice);document.querySelector('#saveAccountBtn')?.addEventListener('click',saveAccount);document.querySelector('#saveTransactionBtn')?.addEventListener('click',saveTransaction);document.querySelector('#runAkinsoftImportBtn')?.addEventListener('click',importAkinsoft);document.addEventListener('click',e=>{const b=e.target.closest('[data-approve-count]');if(b)approveCount(b.dataset.approveCount)});const d=document.querySelector('#accountingInvoiceDate');if(d)d.value=new Date().toISOString().slice(0,10)}
 return{openView,bind,renderStock};
})();
