const CloudSync=(()=>{let client=null;async function cfg(){return{url:await KDB.setting('sbUrl',''),key:await KDB.setting('sbKey',''),email:await KDB.setting('sbEmail',''),password:await KDB.setting('sbPassword','')}}
async function connect(){const c=await cfg();if(!c.url||!c.key)throw new Error('Supabase URL ve anahtar eksik.');if(!window.supabase?.createClient)throw new Error('Supabase istemcisi yüklenemedi.');client=window.supabase.createClient(c.url,c.key,{auth:{persistSession:true,autoRefreshToken:true}});if(c.email&&c.password){const{error}=await client.auth.signInWithPassword({email:c.email,password:c.password});if(error)throw error}return client}
function safe(v){return v===undefined?null:v}
async function pushTable(table,rows,map){if(!rows.length)return;const payload=rows.map(map);const{error}=await client.from(table).upsert(payload,{onConflict:'local_id'});if(error)throw error}
async function sync(user){await connect();const products=await KDB.all('products'),receipts=await KDB.all('receipts'),lines=await KDB.all('receiptLines'),suppliers=await KDB.all('suppliers'),logs=await KDB.all('auditLogs');
await pushTable('products',products,p=>({local_id:p.barcode,barcode:p.barcode,product_code:safe(p.productCode),product_name:p.productName,unit:safe(p.unit),case_quantity:safe(p.caseQuantity),box_quantity:safe(p.boxQuantity),purchase_price:safe(p.purchasePrice),manually_added:!!p.manuallyAdded,manually_defined_unit:!!p.manuallyDefinedUnit,notes:safe(p.notes),updated_at:p.updatedAt||new Date().toISOString()}));
await pushTable('suppliers',suppliers,s=>({local_id:s.id,name:s.name,phone:safe(s.phone),tax_number:safe(s.taxNumber),notes:safe(s.notes),updated_at:s.updatedAt||new Date().toISOString()}));
await pushTable('receipts',receipts,r=>({local_id:r.id,supplier_name:safe(r.supplierName),invoice_number:safe(r.invoiceNumber),receipt_date:r.receiptDate,employee_name:safe(r.employeeName),description:safe(r.description),status:r.status,total_lines:r.lineCount||0,total_units:r.totalUnits||0,created_at:r.createdAt,updated_at:r.updatedAt||r.createdAt}));
await pushTable('receipt_lines',lines,l=>({local_id:l.id,receipt_local_id:l.receiptId,barcode:l.barcode,product_code:safe(l.productCode),product_name:l.productName,entered_quantity:l.quantity,entered_unit:l.unit,conversion_quantity:l.conversion,total_units:l.totalUnits,purchase_price:safe(l.purchasePrice),created_at:l.createdAt,updated_at:l.updatedAt||l.createdAt}));
await pushTable('audit_logs',logs,l=>({local_id:l.id,user_name:l.userName,action:l.action,entity_type:l.entityType,entity_local_id:safe(l.entityId),description:l.description,old_value:safe(l.oldValue),new_value:safe(l.newValue),created_at:l.createdAt}));
await KDB.setSetting('lastSyncAt',new Date().toISOString());await KDB.log(user,'SYNC','system','cloud','Bulut senkronizasyonu tamamlandı.');return true}
return{sync,connect}})();
